# set up active profile
spring:
  profiles:
    active: development

# set up jwt
security:
  jwt:
    token:
      secret-key: 67898682BE68ED0DC883CB5B5C96D2BCDF8B4670435AA20FABFEB9846E077760

# set up the cloudinary
cloudinary:
  cloud-name: dx97yn40v
  api-key: 885826543631441
  api-secret: nYUc9V4akJUAzK2b7Gf7lcE-ENY

# set up the swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs

base:
  url: http://localhost:8080

# set up the stripe
stripe:
  secret:
    key: sk_test_51NjhWBBw2ItUGB0m5op5hLYTpvOGvmNNDOOS2e1XLCNmWFe2udfuuT2GyiIDwbwxAoDk7Ako36cgtmQVnWJYhJTw00lEtvKTt4

# set up actuators
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true

# Properties for the "development" profile
---
spring:
  config:
    activate:
      on-profile: development
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      timeout: 60000ms

    mongodb:
      uri: mongodb://localhost:27017/ecommerce

  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:/}

# Properties for the "docker" profile
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://app-db:3306/ecommerce
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  data:
    redis:
      database: 0
      host: app-redis
      port: 6379
      timeout: 60000ms

    mongodb:
      uri: mongodb://app-mongodb:27017/ecommerce

  rabbitmq:
    host: app-rabbitmq
    port: 5672
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:/}
