spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

security:
  jwt:
    token:
      secret-key: 67898682BE68ED0DC883CB5B5C96D2BCDF8B4670435AA20FABFEB9846E077760






