name: Testing

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['6.0']
    env:
      RABBITMQ_PORT: 5673

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_DATABASE: ecommerce
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      rabbitmq:
        image: rabbitmq:3.8
        ports:
          - 5672:5672
        options: --health-cmd="rabbitmqctl node_health_check" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis:6.2
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Start MySQL
        run: |
          docker run -d --name mysql -p 3307:3306 -e MYSQL_ROOT_PASSWORD=admin -e MYSQL_DATABASE=ecommerce mysql:8.0

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: test-rs
          mongodb-port: 27017

      - name: Start RabbitMQ
        run: |
          docker run -d --name rabbitmq -p 5673:5672 -p 15672:15672 rabbitmq:3-management

      - name: Start Redis
        run: |
          docker run -d --name redis -p 6380:6379 redis:6.2

      - name: Build with Maven
        run: mvn -B -Dspring.config.location=src/main/resources/application.yml clean package

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

      - name: Run tests with Maven
        run: mvn -B -Dspring.config.location=src/main/resources/application.yml test

      - name: Stop MySQL
        run: |
          docker stop mysql
          docker rm mysql

      - name: Stop MongoDB
        run: |
          docker stop mongodb
          docker rm mongodb

      - name: Stop RabbitMQ
        run: |
          docker stop rabbitmq
          docker rm rabbitmq

      - name: Stop Redis
        run: |
          docker stop redis
          docker rm redis